### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by PlasterPate** [andrazznidar/bbb-player#7]
When I tried downloading the meeting, a UnicodeDecodeError occured:
`Traceback (most recent call last):
  File "bbb-player.py", line 332, in <module>
    downloadSlides(baseURL, folderPath)
  File "bbb-player.py", line 83, in downloadSlides
    data = json.load(f)
  File "C:\Users\javan\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\Users\javan\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 112: character maps to <undefined>
`

I solved the error by changing line 82 of bbb-player.py from:
`with open(basePath + '/presentation_text.json') as f:`
to
`with open(basePath + '/presentation_text.json', encoding="utf8") as f:`

**Comment by andrazznidar** [comment]
Thanks for the report and the fix. I have implemented the fix in PR #8 and merged it to the main branch.
